//// Replays the SharedMap merge-semantics corpus (plan M2) against
//// `watershed/map_kernel`.
////
//// The fixtures in `test/fixtures/corpus/` are generated by the TS oracle
//// harness on the `feat/map-corpus-harness` branch of the FluidFramework
//// checkout (`packages/dds/map/src/test/mocha/corpusGenerator.spec.ts`); see
//// the README next to the fixtures for the format and replay contract. Do
//// not hand-edit them — regenerate and re-copy.
////
//// The replayer models the reference harness's system: each client is a
//// kernel instance plus an event log, sharing one global FIFO queue that
//// stands in for the server's total order. Delivering a message acks it on
//// the originating client and applies it remotely everywhere else. At each
//// `check` step the entries (including iteration order) and the events
//// emitted since the previous check must match the oracle exactly.

import gleam/dict.{type Dict}
import gleam/dynamic/decode.{type Decoder}
import gleam/int
import gleam/json.{type Json}
import gleam/list
import gleam/option.{None, Some}
import gleam/string
import simplifile
import startest.{describe, it}
import startest/expect
import startest/test_tree.{type TestTree}
import watershed/map_kernel.{
  type MapEvent, type MapOp, type MapState, Cleared, ValueChanged,
}

const corpus_dir = "test/fixtures/corpus"

pub fn map_kernel_corpus_tests() -> TestTree {
  let assert Ok(files) = simplifile.read_directory(corpus_dir)
  let scenario_files =
    files
    |> list.filter(string.ends_with(_, ".json"))
    |> list.sort(string.compare)
  let assert False = scenario_files == []
    as "no corpus fixtures found — see test/fixtures/corpus/README.md"
  describe(
    "map_kernel corpus",
    list.map(scenario_files, fn(file) {
      it(file, fn() { load_scenario(file) |> replay })
    }),
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Corpus file format
// ─────────────────────────────────────────────────────────────────────────────

type Step {
  SetStep(client: String, key: String, value: Json)
  DeleteStep(client: String, key: String)
  ClearStep(client: String)
  ProcessSome(count: Int)
  ProcessAll
  Check
}

type ClientObservation {
  ClientObservation(entries: List(#(String, Json)), events: List(MapEvent))
}

type Observation {
  Observation(
    after_step: Int,
    converged: Bool,
    clients: Dict(String, ClientObservation),
  )
}

type Scenario {
  Scenario(
    name: String,
    clients: List(String),
    steps: List(Step),
    observations: List(Observation),
  )
}

fn load_scenario(file: String) -> Scenario {
  let assert Ok(text) = simplifile.read(corpus_dir <> "/" <> file)
  case json.parse(text, scenario_decoder()) {
    Ok(scenario) -> scenario
    Error(error) ->
      panic as { "failed to decode " <> file <> ": " <> string.inspect(error) }
  }
}

fn scenario_decoder() -> Decoder(Scenario) {
  use format_version <- decode.field("formatVersion", decode.int)
  case format_version {
    1 -> {
      use name <- decode.field("name", decode.string)
      use clients <- decode.field("clients", decode.list(decode.string))
      use steps <- decode.field("steps", decode.list(step_decoder()))
      use observations <- decode.field(
        "observations",
        decode.list(observation_decoder()),
      )
      decode.success(Scenario(name:, clients:, steps:, observations:))
    }
    _ -> decode.failure(Scenario("", [], [], []), "formatVersion 1")
  }
}

fn step_decoder() -> Decoder(Step) {
  use action <- decode.field("action", decode.string)
  case action {
    "set" -> {
      use client <- decode.field("client", decode.string)
      use key <- decode.field("key", decode.string)
      use value <- decode.field("value", value_decoder())
      decode.success(SetStep(client:, key:, value:))
    }
    "delete" -> {
      use client <- decode.field("client", decode.string)
      use key <- decode.field("key", decode.string)
      decode.success(DeleteStep(client:, key:))
    }
    "clear" -> {
      use client <- decode.field("client", decode.string)
      decode.success(ClearStep(client:))
    }
    "processSome" -> {
      use count <- decode.field("count", decode.int)
      decode.success(ProcessSome(count:))
    }
    "processAll" -> decode.success(ProcessAll)
    "check" -> decode.success(Check)
    _ -> decode.failure(Check, "Step")
  }
}

fn observation_decoder() -> Decoder(Observation) {
  use after_step <- decode.field("afterStep", decode.int)
  use converged <- decode.field("converged", decode.bool)
  use clients <- decode.field(
    "clients",
    decode.dict(decode.string, client_observation_decoder()),
  )
  decode.success(Observation(after_step:, converged:, clients:))
}

fn client_observation_decoder() -> Decoder(ClientObservation) {
  use entries <- decode.field("entries", decode.list(entry_decoder()))
  use events <- decode.field("events", decode.list(event_decoder()))
  decode.success(ClientObservation(entries:, events:))
}

/// Entries are serialized as two-element arrays: `["key", value]`.
fn entry_decoder() -> Decoder(#(String, Json)) {
  decode.list(decode.dynamic)
  |> decode.then(fn(pair) {
    case pair {
      [key, value] ->
        case
          decode.run(key, decode.string),
          decode.run(value, value_decoder())
        {
          Ok(key), Ok(value) -> decode.success(#(key, value))
          _, _ -> decode.failure(#("", json.null()), "Entry")
        }
      _ -> decode.failure(#("", json.null()), "Entry")
    }
  })
}

/// Expected events decode straight into kernel `MapEvent`s; `previousValue`
/// is omitted by the oracle when the reference implementation reported
/// `undefined`, which maps to `None`.
fn event_decoder() -> Decoder(MapEvent) {
  use event <- decode.field("event", decode.string)
  use local <- decode.field("local", decode.bool)
  case event {
    "valueChanged" -> {
      use key <- decode.field("key", decode.string)
      use previous <- decode.optional_field(
        "previousValue",
        None,
        value_decoder() |> decode.map(Some),
      )
      decode.success(ValueChanged(key, previous, None, local))
    }
    "clear" -> decode.success(Cleared(local))
    _ -> decode.failure(Cleared(local), "Event")
  }
}

/// Erase the `value` field the oracle corpus does not record (see the
/// comparison in `run_check`).
fn erase_event_value(event: MapEvent) -> MapEvent {
  case event {
    ValueChanged(key, previous, _, local) ->
      ValueChanged(key, previous, None, local)
    Cleared(_) -> event
  }
}

/// Arbitrary JSON re-built as `gleam/json.Json`. Both scenario inputs and
/// expected outputs pass through this same decoder, so structural equality
/// on the resulting `Json` values is sound.
fn value_decoder() -> Decoder(Json) {
  use <- decode.recursive
  let non_null =
    decode.one_of(decode.int |> decode.map(json.int), or: [
      decode.float |> decode.map(json.float),
      decode.bool |> decode.map(json.bool),
      decode.string |> decode.map(json.string),
      decode.list(value_decoder()) |> decode.map(json.preprocessed_array),
      decode.dict(decode.string, value_decoder())
        |> decode.map(fn(fields) { json.object(dict.to_list(fields)) }),
    ])
  decode.optional(non_null)
  |> decode.map(option.unwrap(_, json.null()))
}

// ─────────────────────────────────────────────────────────────────────────────
// Replay harness (models the reference MockContainerRuntimeFactory system)
// ─────────────────────────────────────────────────────────────────────────────

type ClientSim {
  ClientSim(state: MapState, log: List(MapEvent))
}

type Sim {
  Sim(clients: Dict(String, ClientSim), queue: List(#(String, MapOp)))
}

fn replay(scenario: Scenario) -> Nil {
  let clients =
    scenario.clients
    |> list.map(fn(id) { #(id, ClientSim(map_kernel.new(), [])) })
    |> dict.from_list
  let sim =
    list.index_fold(
      scenario.steps,
      Sim(clients:, queue: []),
      fn(sim, step, index) { run_step(sim, scenario, step, index) },
    )
  // Mirrors the generator's end-of-scenario assertion.
  sim.queue |> expect.to_equal([])
}

fn run_step(sim: Sim, scenario: Scenario, step: Step, index: Int) -> Sim {
  case step {
    SetStep(client, key, value) ->
      submit(sim, client, fn(state) { map_kernel.set(state, key, value) })
    DeleteStep(client, key) ->
      submit(sim, client, fn(state) { map_kernel.delete(state, key) })
    ClearStep(client) -> submit(sim, client, map_kernel.clear)
    ProcessSome(count) -> process(sim, scenario, count)
    ProcessAll -> process(sim, scenario, list.length(sim.queue))
    Check -> check(sim, scenario, index)
  }
}

/// Apply a local op optimistically on the issuing client and append the op
/// to the global sequencing queue.
fn submit(
  sim: Sim,
  client_id: String,
  operate: fn(MapState) -> #(MapState, List(MapEvent), MapOp),
) -> Sim {
  let client = get_client(sim, client_id)
  let #(state, events, op) = operate(client.state)
  Sim(
    clients: dict.insert(
      sim.clients,
      client_id,
      ClientSim(state:, log: list.append(client.log, events)),
    ),
    queue: list.append(sim.queue, [#(client_id, op)]),
  )
}

/// Pop `count` messages off the head of the queue (the server's total order)
/// and deliver each to every client.
fn process(sim: Sim, scenario: Scenario, count: Int) -> Sim {
  case count, sim.queue {
    0, _ -> sim
    _, [] -> panic as "corpus step processes more messages than outstanding"
    _, [#(origin, op), ..rest] -> {
      let clients =
        list.fold(scenario.clients, sim.clients, fn(clients, client_id) {
          let assert Ok(client) = dict.get(clients, client_id)
          let client = case client_id == origin {
            // The originating client treats the message as an ack of its
            // oldest matching pending op; acks never emit events.
            True ->
              case map_kernel.ack_local(client.state, op) {
                Ok(state) -> ClientSim(..client, state:)
                Error(error) ->
                  panic as {
                    "ack mismatch on client "
                    <> client_id
                    <> ": "
                    <> string.inspect(error)
                  }
              }
            False -> {
              let #(state, events) = map_kernel.apply_remote(client.state, op)
              ClientSim(state:, log: list.append(client.log, events))
            }
          }
          dict.insert(clients, client_id, client)
        })
      process(Sim(clients:, queue: rest), scenario, count - 1)
    }
  }
}

/// Compare every client against the oracle observation for this step, then
/// drain the event logs (events are recorded "since the previous check").
fn check(sim: Sim, scenario: Scenario, step_index: Int) -> Sim {
  let observation = case
    list.find(scenario.observations, fn(observation) {
      observation.after_step == step_index
    })
  {
    Ok(observation) -> observation
    Error(_) ->
      panic as {
        "no observation for check at step " <> int.to_string(step_index)
      }
  }

  let clients =
    list.fold(scenario.clients, sim.clients, fn(clients, client_id) {
      let assert Ok(client) = dict.get(clients, client_id)
      let expected = case dict.get(observation.clients, client_id) {
        Ok(expected) -> expected
        Error(_) ->
          panic as {
            "observation at step "
            <> int.to_string(step_index)
            <> " is missing client "
            <> client_id
          }
      }
      map_kernel.entries(client.state) |> expect.to_equal(expected.entries)
      // The oracle corpus predates the event's `value` field, so compare
      // with it erased; `value` correctness is pinned by map_kernel_test.
      client.log
      |> list.map(erase_event_value)
      |> expect.to_equal(expected.events)
      dict.insert(clients, client_id, ClientSim(..client, log: []))
    })

  // When the queue is drained the oracle asserts convergence; assert our own.
  case observation.converged {
    True -> {
      sim.queue |> expect.to_equal([])
      let views =
        list.map(scenario.clients, fn(client_id) {
          let assert Ok(client) = dict.get(clients, client_id)
          map_kernel.entries(client.state)
        })
      case views {
        [first, ..rest] ->
          list.each(rest, fn(view) { view |> expect.to_equal(first) })
        [] -> Nil
      }
    }
    False -> Nil
  }

  Sim(..sim, clients:)
}

fn get_client(sim: Sim, client_id: String) -> ClientSim {
  case dict.get(sim.clients, client_id) {
    Ok(client) -> client
    Error(_) -> panic as { "scenario references unknown client " <> client_id }
  }
}
